# Typos configuration (minimal, conservative)
# - Avoid scanning locales and OS release fingerprints
# - Recognize a few project-specific proper nouns

[files]
extend-exclude = [
  "src/**",
  "locales/**",
  "src/steps/os/os_release/**",
]

[default]
extend-ignore-words = [
  # Project/tooling names
  "Topgrade", "Pengwin", "WSL", "CodeQL", "OSV", "SBOM", "Trivy",
  "cargo-deny", "rustfmt", "Homebrew", "winget", "AUR",
  "lychee", "dprint", "markdownlint", "pre-commit",
]
