# Typos configuration (minimal, conservative)
# Exclude locales and OS fingerprint data to avoid false positives
# - Recognize a few project-specific proper nouns

[files]
extend-exclude = [
  "locales/**",
  # Include only English locale files - TODO: Split English into a Separate File
  #"!locales/en/**"
]

[default]
extend-ignore-words = [
  # Project/tooling names
  "Pengwin",
  "PENGWIN",
]
