# Typos configuration (minimal, conservative)
# Exclude locales and OS fingerprint data to avoid false positives
# - Recognize a few project-specific proper nouns

[files]
extend-exclude = [
  "src/steps/os/os_release/**",
  "locales/**",
  # Include only English locale files - TODO: Split locales/app.yml into a Separate english File
  # "!locales/en/**"
]

[default]
# Mark specific words as always valid by mapping them to themselves
check-file = true
check-filename = true

[default.extend-words]
# Add project-specific terms that should not be flagged as typos
# Example: topgrade = "topgrade"
