# OSV-Scanner configuration file
# proc-macro-error is compile-time only dependency with no runtime security risk
# Used via merge crate which would require major code refactoring to replace

[[IgnoredVulns]]
id = "RUSTSEC-2024-0370"
reason = "Compile-time only dependency via proc-macro, no runtime security risk"
